// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package flaggio

type Evaluation struct {
	FlagKey    string        `json:"flagKey"`
	Value      interface{}   `json:"value"`
	Version    int           `json:"version"`
	StackTrace []*StackTrace `json:"stackTrace"`
}

type StackTrace struct {
	Type   string      `json:"type"`
	ID     string      `json:"id"`
	Answer interface{} `json:"answer"`
}
