// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package flaggio

type Evaluation struct {
	FlagKey string      `json:"flagKey"`
	Value   interface{} `json:"value"`
	Version int         `json:"version"`
}
