name: Dependabot mod & vendor fix
on:
  push:
    branches:
      # Only run on dependabot Go branches
      - 'dependabot/go_modules/**'
jobs:
  fix:
    runs-on: ubuntu-latest
    container: 'golang:1.14'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Fix detached HEAD
        run: git checkout ${GITHUB_REF#refs/heads/} # https://github.com/actions/checkout/issues/6
      - name: Tidy
        run: |
          go mod tidy
          go mod vendor
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_FIX_GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit --amend --no-edit
            git push --force-with-lease
          fi
